services:
  mysql:
    image: mysql:8.4
    env_file:
      - .env.backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./viajerodump.sql:/docker-entrypoint-initdb.d/init-db.sql 
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=1g
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network
    restart: unless-stopped
    command: --default-time-zone='+00:00'

  nestjs-app:
    image: ${BACK_IMAGE}
    ports:
      - "${BACK_PORT}:3000"
    env_file:
      - .env.backend
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true

volumes:
  mysql-data:
    driver: local