# ------------------------------instalando pnpm------------------------------
FROM node:20-alpine as base
# Instalando pnpm
RUN npm i -g pnpm

WORKDIR /app

# ------------------------------instalando dependencias------------------------------
FROM base as dependencies

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# ------------------------------build stage------------------------------
FROM base as build

WORKDIR /app
COPY package*.json tsconfig*.json nest-cli.json .eslintrc.js ./
COPY src/ ./src/
COPY test/ ./test/
COPY --from=dependencies /app/node_modules ./node_modules
RUN pnpm build

# ------------------------------deploy stage------------------------------
FROM base as deploy

WORKDIR /app
COPY --from=build /app/dist/ ./dist/
COPY --from=build /app/node_modules ./node_modules
COPY package.json tsconfig*.json nest-cli.json ./

# Configuramos las variables de entorno
ENV NODE_ENV=dev

EXPOSE 3000
CMD ["node", "dist/main"]