export enum TipoObservacion {
	COMODIDADES_SERVICIOS_ESTABLECIMIENTO = 1,
	TIPO_CANCHA_DEPORTIVA = 2,
	POLITICA_GARANTIA = 3,
	REGISTRO_ACTIVIDADES = 4,
	COMODIDADES_DETALLE_OFERTA = 5,
	NORMAS = 6,
	DOMICILIOS = 7,
	REGISTRO_EVENTOS = 8,
	CARACTERISTICAS_DE_LA_VIVIENDA = 9,
}
